[package]
name = "alumina_image_data"
version = "0.1.0"
authors = ["zza <millard.jn@gmail.com>"]
edition = "2018"

[dependencies]
alumina = { path = "../" }
ndarray = "0.12.1"
walkdir = "2.2"
image = "0.20"