[package]
name = "alumina_image_data"
version = "0.3.0"
authors = ["zza <millard.jn@gmail.com>"]
edition = "2018"

[dependencies]
alumina_data = { path = "../alumina_data", version = "0.3" }
ndarray = { version = "0.15", features = ["rayon", "serde-1"] }
walkdir = "2.2"
image = "0.23"