[package]
name = "alumina_data"
version = "0.3.0"
authors = ["zza <millard.jn@gmail.com>"]
edition = "2018"


[dependencies]
alumina_core = { path = "../alumina_core" }

indexmap = "1"
ndarray = {version = "0.13", features = ["rayon"]}
rand = "0.7"
rand_pcg = "*"
smallvec = "1.3"
byteorder = "1.3"